Задачи 2 блока
js-tasks-ru/js-20211109_anastasiya75 pull request #2
Opened 2021-11-13 17:18 UTC by stasyakalinina

2021-11-13 17:20 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-14 17:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const compareFn = (a, b) => a.localeCompare(b, ['ru', 'en'], {sensitivity: 'variant', caseFirst: 'upper'});
good 👍

2021-11-14 17:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return resArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-11-14 17:17 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  }
если не сработает ни одно из `if` условий, что вернет функция?

2021-11-14 17:17 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return Object.fromEntries(Object.entries(obj).filter(([key]) => fields.includes(key)));
👍 good

2021-11-14 17:17 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  return Object.fromEntries(Object.entries(obj).filter(([key]) => !fields.includes(key)));
👍 good

2021-11-14 17:18 UTC, dosandk requested changes
👍 good
В решении `sortStrings` следует избавиться от вызова `reverse`

2021-11-15 07:32 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-15 10:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-11-16 09:50 UTC, dosandk approved these changes
good 👍

2021-11-16 09:50 UTC, merged